### ISSUE TITLE
Messages are not removed from the stream

### ISSUE THREAD

**Issue by bobsingor** [hoekma/redpop#35]
First of all, thanks a lot for making this library. This makes things so much easier.

I am having 2 consumers on the same stream.
After the message is processed I return true and I see in your code that you are doing a XACK.

In my memory graph i see that the memory is keep going up and it looks like that the memory is not being cleared. 
I thought that XACK would remove the message from the stream. 

In my current situation it looks like that after couple of days my redis server runs out of memory.

Do you have more insight on this?

**Comment by hoekma** [comment]
Hi Bob- events are not removed from the stream on an XACK because other consumers may need to still process those events.  For instance, you may have a stream that contains customer data and two different consumers (one for updating the order entry system and one for updating the accounting system) that do different things with that same information. If one consumer deletes the event, the other one may not be able to do its processing.  This use case is different than having multiple instances of the same consumer for the purpose of horizontal scaling.  

To accomplish what you're trying to do, there are two ways to remove the message from the stream:  

- The first is to issue an `xdel` of the event ID (so in your consumer's processEvent() you can do a  `this.xdel(message-id)`.  This will delete the message currently being processed immediately.   
- The other way is issue an `xtrim` of the stream to tell it the maximum number of messages to keep, which will trim the oldest messages in the stream.  You can do that with `this.xtrim(maxcount)` where maxcount is an integer.  So if you say xtrim(1000) in consumer::onBatchesComplete(), your stream will always be kept at 1000 messages plus any unprocessed messages.

**Comment by hoekma** [comment]
Hi @bobsingor  - Checking in to see if this helped and whether I can close this issue.
